version: '3.1'

services:
  db:
    image: postgres:12-alpine
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my-course
      POSTGRES_USER: my-user
    ports:
      - "5432:5432"
